/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.hotelaps.view;

/**
 *
 * @author Gabriel Rosero ESPE-DCCO
 */
public class FrmAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdminMenu
     */
    public FrmAdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        room1 = new javax.swing.JLabel();
        room2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbrShop = new javax.swing.JMenu();
        mimAdd = new javax.swing.JMenuItem();
        mimShow = new javax.swing.JMenuItem();
        mbrRooms = new javax.swing.JMenu();
        mimCreateRoom = new javax.swing.JMenuItem();
        mimShorRoom = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        room1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        room1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room1.setText("Bienvenido al sistema");

        room2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        room2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room2.setText("administrador");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/hotelaps/files/aprendizaje-3.png"))); // NOI18N

        mbrShop.setText("APSShop");

        mimAdd.setText("Agregar");
        mimAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimAddActionPerformed(evt);
            }
        });
        mbrShop.add(mimAdd);

        mimShow.setText("Revisar");
        mimShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimShowActionPerformed(evt);
            }
        });
        mbrShop.add(mimShow);

        jMenuBar1.add(mbrShop);

        mbrRooms.setText("Habitaciones");

        mimCreateRoom.setText("Crear habitacion");
        mimCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimCreateRoomActionPerformed(evt);
            }
        });
        mbrRooms.add(mimCreateRoom);

        mimShorRoom.setText("Ver habitaciones existentes");
        mimShorRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimShorRoomActionPerformed(evt);
            }
        });
        mbrRooms.add(mimShorRoom);

        jMenuBar1.add(mbrRooms);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(room1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(room2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(room1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(room2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mimShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimShowActionPerformed
        FrmShowProduct product = new FrmShowProduct();
        this.setVisible(false);
        product.setVisible(true);
    }//GEN-LAST:event_mimShowActionPerformed

    private void mimShorRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimShorRoomActionPerformed
        FrmShowRooms room = new FrmShowRooms();
        this.setVisible(false);
        room.setVisible(true);
    }//GEN-LAST:event_mimShorRoomActionPerformed

    private void mimCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimCreateRoomActionPerformed
        FrmRegisterRoom room = new FrmRegisterRoom();
        this.setVisible(false);
        room.setVisible(true);
    }//GEN-LAST:event_mimCreateRoomActionPerformed

    private void mimAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimAddActionPerformed
        FrmRegisterProduct product = new FrmRegisterProduct();
        this.setVisible(false);
        product.setVisible(true);
    }//GEN-LAST:event_mimAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbrRooms;
    private javax.swing.JMenu mbrShop;
    private javax.swing.JMenuItem mimAdd;
    private javax.swing.JMenuItem mimCreateRoom;
    private javax.swing.JMenuItem mimShorRoom;
    private javax.swing.JMenuItem mimShow;
    private javax.swing.JLabel room1;
    private javax.swing.JLabel room2;
    // End of variables declaration//GEN-END:variables
}
