/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.hotelaps.view;

/**
 *
 * @author Gabriel Rosero ESPE-DCCO
 */
public class FrmPrincipalMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipalMenu
     */
    public FrmPrincipalMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbrCustomerRegister = new javax.swing.JMenu();
        mimCustomerRegister = new javax.swing.JMenuItem();
        mbrAccesSistem = new javax.swing.JMenu();
        mimCustomerLoggin = new javax.swing.JMenuItem();
        mimAdminLoggin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO A HOTEL APS");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/hotelaps/files/WhatsApp Image 2021-03-02 at 23.46.40.jpeg"))); // NOI18N

        mbrCustomerRegister.setText("Cliente");

        mimCustomerRegister.setText("Crear");
        mimCustomerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimCustomerRegisterActionPerformed(evt);
            }
        });
        mbrCustomerRegister.add(mimCustomerRegister);

        jMenuBar1.add(mbrCustomerRegister);

        mbrAccesSistem.setText("Ingresar");

        mimCustomerLoggin.setText("Cliente");
        mimCustomerLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimCustomerLogginActionPerformed(evt);
            }
        });
        mbrAccesSistem.add(mimCustomerLoggin);

        mimAdminLoggin.setText("Administrador");
        mimAdminLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimAdminLogginActionPerformed(evt);
            }
        });
        mbrAccesSistem.add(mimAdminLoggin);

        jMenuBar1.add(mbrAccesSistem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mimCustomerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimCustomerRegisterActionPerformed
        FrmRegisterCustomer customer = new FrmRegisterCustomer();
        this.setVisible(false);
        customer.setVisible(true);
    }//GEN-LAST:event_mimCustomerRegisterActionPerformed

    private void mimCustomerLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimCustomerLogginActionPerformed
        FrmClientLoggin customerLoggin = new FrmClientLoggin();
        this.setVisible(false);
        customerLoggin.setVisible(true);
    }//GEN-LAST:event_mimCustomerLogginActionPerformed

    private void mimAdminLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimAdminLogginActionPerformed
        FrmWorkerLoggin workerLoggin = new FrmWorkerLoggin();
        this.setVisible(false);
        workerLoggin.setVisible(true);
    }//GEN-LAST:event_mimAdminLogginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbrAccesSistem;
    private javax.swing.JMenu mbrCustomerRegister;
    private javax.swing.JMenuItem mimAdminLoggin;
    private javax.swing.JMenuItem mimCustomerLoggin;
    private javax.swing.JMenuItem mimCustomerRegister;
    // End of variables declaration//GEN-END:variables
}
